import type { Metadata } from 'next';
import { Montserrat as LibreSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import AuthProvider from '@/providers/authProvider';
import { ToasterProvider } from '@/providers/toastProvider';
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin';
import { extractRouterConfig } from 'uploadthing/server';
import { ourFileRouter } from './api/uploadthing/core';

export const libreSans = LibreSans({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
  variable: '--libre-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={cn(
            'h-screen bg-background libre-sans antialiased flex overflow-hidden'
          )}
        >
          <ToasterProvider />

          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
