import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import '../globals.css';
import { cn } from '@/lib/utils';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div
      className={cn(
        'min-h-screen bg-background font-sans antialiased justify-center items-center flex w-full'
      )}
    >
      {children}
    </div>
  );
}
